site_name: 備忘録と雑記
nav:
    - HOME: index.md
    - Python:
        - Anacondaコマンド集: python/anaconda_cmd.md
        - python基本構文: python/general.md
        - 条件分岐if : python/if.md
        - 繰り返し for,while: python/for.md
        - コレクション: python/collection.md
        - pandas: python/pandas.md
        - 平均・分散・中央値など: python/statistic.md
        - 型注釈: python/typehint.md
        - コマンドライン引数: python/commandLine_option.md
        - ちょっとしたプログラム集: python/tips.md
        - Anacondaによる環境構築: python/anaconda_install.md
        - pyenvでの環境構築: python/pyenv.md
    - 自然言語処理:
        - mecabの導入: nlp/mecab.md
        - mecabユーザー辞書の追加: nlp/mecab_add_userdic.md
        - mecabを使用する: nlp/mecab_usage.md
        # - 正規表現: nlp/regex.md
    # - 異常検知:
    #     - 異常検知基礎: anormaly/base.md
    - Markdown:
        - markdown基本: markdown/mkd.md
        - markdown数式: markdown/math.md
        - markdown数式・記号: markdown/math_symbol.md
        - markdown拡張: markdown/mkdocs_md.md
        - markdown例: markdown/mkd_ex.md
        - mkdocsによるwebページの公開: markdown/mkdocs.md
    - Ubuntu: 
        - Ubuntu設定関連: ubuntu/setting.md
        - Ubuntuコマンド集: ubuntu/cmd.md
        - 2TB以上のHDDのマウント: ubuntu/hdd_mnt.md
        - GPU for tensorflow-gpu: ubuntu/gpu.md
        - ログインループの対処: ubuntu/login_loop.md
    - Windows:
        - WSL導入: windows/wsl.md
        - WSL ~matplotlib~ : windows/wsl_matplotlib.md
        - Xming文字化け対処: windows/xming_char.md
    - RestructuredText:
        - Rest基本構文: rest/fund.md
        - 注意・強調: rest/admotions.md
        - リンク・脚注: rest/link.md
        - 数式の挿入: rest/math.md
        - コード・表・画像・サイドバー: rest/module.md
        - その他: rest/other.md
        - sphinxによるwebページの公開: rest/sphinx.md
    - その他:
        - git: other/git.md
    - 雑記: 
        - 2019年4月: blog/201904.md
    - 免責事項: disclaimer.md

# theme: readthedocs
theme:
  name: 'material'
  language: 'ja'
  feature:
    tabs: False
extra:
    search:
        language: 'ja'

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
    - "css/custom.css"

# extra_css: [css/custom.css]

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - codehilite:
        linenums : true
        use_pygments: true
        noclasses: true
        pygments_style: monokai
    - def_list
    - footnotes
    - admonition

# extra_javascript: 
#     - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
